question_data = [
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "The color orange is named after the fruit.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "When you cry in space, your tears stick to your face.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "The Lego Group was founded in 1932.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "Ping-Pong originated in England",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "Adolf Hitler was born in Australia. ",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "General Knowledge",
                "question": "The Great Wall of China is visible from the moon.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
        ]
